package il.cshaifasweng.OCSFMediatorExample.entities.dataTypes;

public enum MovieGenre {
    ACTION, ADVENTURE, ANIMATION, BIOGRAPHY, COMEDY, CRIME, DOCUMENTARY, DRAMA, FAMILY, FANTASY, FILM_NOIR, HISTORY, HORROR, MUSIC, MUSICAL, MYSTERY, ROMANCE, SCI_FI, SHORT, SPORT, SUPERHERO, THRILLER, WAR, WESTERN,
    ROM_COM, DYSTOPIAN, DANCE, EXPERIMENTAL, SLASHER, BIOPIC, ROAD, PARODY, SATIRE, TRAGEDY
}
