package il.cshaifasweng.OCSFMediatorExample.entities;

// This enum represents the countries that are available in the system
// Automatically generated

public enum Country {
    ISRAEL, USA, UK, FRANCE, GERMANY, ITALY, SPAIN, CHINA, JAPAN, KOREA, INDIA, RUSSIA, BRAZIL, CANADA, AUSTRALIA, MEXICO, ARGENTINA, SOUTH_AFRICA, NIGERIA, EGYPT, SAUDI_ARABIA, TURKEY, IRAN, IRAQ, SYRIA,
    LEBANON, JORDAN, PALESTINE, AFGHANISTAN, ALBANIA, ALGERIA, ANDORRA, ANGOLA, ANTIGUA_AND_BARBUDA, ARMENIA, AUSTRIA, AZERBAIJAN, BAHAMAS, BAHRAIN, BANGLADESH, BARBADOS, BELARUS, BELGIUM, BELIZE, BENIN, BHUTAN,
    BOLIVIA, BOSNIA_AND_HERZEGOVINA, BOTSWANA, BRUNEI, BULGARIA, BURKINA_FASO, BURUNDI, CABO_VERDE, CAMBODIA, CAMEROON, CENTRAL_AFRICAN_REPUBLIC, CHAD, CHILE, COLOMBIA, COMOROS, CONGO, COSTA_RICA, CROATIA,
    CUBA, CYPRUS, CZECH_REPUBLIC, DENMARK, DJIBOUTI, DOMINICA, DOMINICAN_REPUBLIC, ECUADOR, EL_SALVADOR, EQUATORIAL_GUINEA, ERITREA, ESTONIA, ESWATINI, ETHIOPIA, FIJI, FINLAND, GABON, GAMBIA, GEORGIA, GHANA,
    GREECE, GRENADA, GUATEMALA, GUINEA, GUINEA_BISSAU, GUYANA, HAITI, HONDURAS, HUNGARY, ICELAND, INDONESIA, IRELAND, IVORY_COAST, JAMAICA, KAZAKHSTAN, KENYA, KIRIBATI, KOSOVO, KUWAIT, KYRGYZSTAN, LAOS, LATVIA,
    LESOTHO, LIBERIA, LIBYA, LIECHTENSTEIN, LITHUANIA, LUXEMBOURG, MADAGASCAR, MALAWI, MALAYSIA, MALDIVES, MALI, MALTA, MARSHALL_ISLANDS, MAURITANIA, MAURITIUS, MICRONESIA, MOLDOVA, MONACO, MONGOLIA, MONTENEGRO,
    MOROCCO, MOZAMBIQUE, MYANMAR, NAMIBIA, NAURU, NEPAL, NETHERLANDS, NEW_ZEALAND, NICARAGUA, NIGER, NORTH_MACEDONIA, NORWAY, OMAN, PAKISTAN, PALAU, PANAMA, PAPUA_NEW_GUINEA, PARAGUAY, PERU, PHILIPPINES, POLAND,
    PORTUGAL, QATAR, ROMANIA, RWANDA, SAINT_KITTS_AND_NEVIS, SAINT_LUCIA, SAINT_VINCENT_AND_THE_GRENADINES, SAMOA, SAN_MARINO, SAO_TOME_AND_PRINCIPE, SENEGAL, SERBIA, SEYCHELLES, SIERRA_LEONE, SINGAPORE, SLOVAKIA,
    SLOVENIA, SOLOMON_ISLANDS, SOMALIA, SOUTH_SUDAN, SRI_LANKA, SUDAN, SURINAME, SWEDEN, SWITZERLAND, TAJIKISTAN, TANZANIA, THAILAND, TIMOR_LESTE, TOGO, TONGA, TRINIDAD_AND_TOBAGO, TUNISIA, TURKMENISTAN, TUVALU,
    UGANDA, UKRAINE, UNITED_ARAB_EMIRATES, URUGUAY, UZBEKISTAN, VANUATU, VATICAN_CITY, VENEZUELA, VIETNAM, YEMEN, ZAMBIA, ZIMBABWE
}
