package il.cshaifasweng.OCSFMediatorExample.entities;

public enum Language {
    ENGLISH, HEBREW, ARABIC, RUSSIAN, FRENCH, SPANISH, GERMAN, ITALIAN, CHINESE, JAPANESE, KOREAN, HINDI, TURKISH,
    PORTUGUESE, DUTCH, POLISH, GREEK, SWEDISH, DANISH, NORWEGIAN, FINNISH, CZECH, HUNGARIAN, ROMANIAN, BULGARIAN,
    SERBIAN, CROATIAN, SLOVAK, SLOVENIAN, UKRAINIAN, LITHUANIAN, LATVIAN, ESTONIAN, MALTESE, ICELANDIC, FAROESE, WELSH,
    IRISH, SCOTTISH, BASQUE, CATALAN, GALICIAN, OCCITAN, BRETON, ALBANIAN, MACEDONIAN, BOSNIAN, MONTENEGRIN, KURDISH,
    PERSIAN, PASHTO, URDU, BENGALI, GUJARATI, MARATHI, PUNJABI, TAMIL, TELUGU, KANNADA, MALAYALAM, SINHALA, THAI, LAO,
    KHMER, VIETNAMESE, INDONESIAN, JAVANESE, MALAY, FILIPINO, TAGALOG, BISAYAN, CEBUANO, ILOCANO, HILIGAYNON, WARAY,
    KAPAMPANGAN, PAMPANGAN, BIKOL, PANGASINAN, MARANAO, MAGUINDANAO, TAUSUG, CHAVACANO, ACEHNESE, BALINESE, BATAK,
    BUGINESE, MADURESE, MINANGKABAU, SUNDANESE, SWAHILI, ZULU, XHOSA, AFRIKAANS, AMHARIC, TWI, HAUSA, YORUBA, IGBO,
    MAORI, SAMOAN, TONGAN, FIJIAN, MALAGASY, BURMESE, MONGOLIAN, NEPALI, TIBETAN, UZBEK, KAZAKH, KYRGYZ, TAJIK, TURKMEN,
    GEORGIAN, ARMENIAN, AZERBAIJANI, HAWAIIAN, LUXEMBOURGISH, MANDARIN, CANTONESE, TAIWANESE,
    QUECHUA, AYMARA, GUARANI, MAPUDUNGUN, NAHUATL, ZAPOTEC, MIXTEC, MAYA, INUIT, SAMI
}